CREATE TABLE IF NOT EXISTS QUESTION(
    id_question INTEGER PRIMARY KEY AUTO_INCREMENT,
    question TEXT NOT NULL,
    reponse TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS REPONSE(
    id_reponse INTEGER PRIMARY KEY AUTO_INCREMENT,
    reponse TEXT NOT NULL,
    id_question INTEGER NOT NULL,
    FOREIGN KEY (id_question) REFERENCES QUESTION(id_question)
);

CREATE TABLE IF NOT EXISTS UTILISATEUR(
    id_utilisateur INTEGER PRIMARY KEY AUTO_INCREMENT,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS QUESTIONNAIRE(
    id_questionnaire INTEGER PRIMARY KEY AUTO_INCREMENT,
    nom TEXT NOT NULL,
    id_utilisateur INTEGER NOT NULL,
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEUR(id_utilisateur)
);

CREATE TABLE IF NOT EXISTS QUESTIONNAIRE_QUESTION(
    id_questionnaire INTEGER NOT NULL,
    id_question INTEGER NOT NULL,
    FOREIGN KEY (id_questionnaire) REFERENCES QUESTIONNAIRE(id_questionnaire),
    FOREIGN KEY (id_question) REFERENCES QUESTION(id_question)
);

